// src/utils/clashroyale/cardImages.js

export const slugifyCardName = (name) =>
    String(name)
        .toLowerCase()
        .replace(/p\.?\s*e\.?\s*k\.?\s*k\.?\s*a/gi, "pekka")
        .replace(/&/g, "and")
        .normalize("NFD")
        .replace(/[\u0300-\u036f]/g, "")
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "");

export const getCardThumbSources = (game, slug) => [
    `/games/${game}/cards/${slug}.webp`,
    `/games/${game}/cards/${slug}.png`,
    `/games/${game}/cards/${slug}.jpg`,
];

// Small 128px webp copies, generated by `npm run thumbs`. Use these anywhere
// many cards appear at once — the card guide lists all 121, and the full-size
// art totals 28.9 MB versus 0.7 MB for these. Falls back to the full image if
// a thumbnail is missing.
export const getCardThumbnailSources = (game, slug) => [
    `/games/${game}/cards/thumb/${slug}.webp`,
    `/games/${game}/cards/${slug}.png`,
];
